export enum Regions {
  ANDALUCIA = 'Andalucía',
  ARAGON = 'Aragón',
  ASTURIAS = 'Asturias, Principado de',
  ISLAS_BALEARES = 'Balears, Illes',
  CANARIAS = 'Canarias',
  CANTABRIA = 'Cantabria',
  CASTILLA_Y_LEON = 'Castilla y León',
  CASTILLA_LA_MANCHA = 'Castilla-La Mancha',
  CATALUÑA = 'Cataluña',
  CEUTA = 'Ceuta',
  COMUNIDAD_VALENCIANA = 'Comunitat Valenciana',
  EXTREMADURA = 'Extremadura',
  GALICIA = 'Galicia',
  MADRID = 'Madrid, Comunidad de',
  MELILLA = 'Melilla',
  MURCIA = 'Murcia, Región de',
  NAVARRA = 'Navarra, Comunidad Foral',
  PAIS_VASO = 'País Vasco',
  LA_RIOJA = 'Rioja, La',
}
